# Generated by Django 4.0.6 on 2022-07-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NottyApp', '0002_testroute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testRoute',
        ),
    ]
